/*
 * This file is part of INAV.
 *
 * INAV is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * INAV is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with INAV.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "platform.h"

#ifdef USE_IOMCU

#include "iomcu.h"
#include "iomcu_protocol.h"
#include "iomcu_uploader.h"

#include "drivers/serial.h"
#include "drivers/serial_uart.h"
#include "drivers/time.h"
#include "drivers/system.h"

#include "io/serial.h"

#include "common/crc.h"
#include "common/utils.h"
#include "common/log.h"

#include <string.h>

// Embedded firmware binary (generated by build system)
extern const uint8_t iomcu_firmware_bin[];
extern const uint32_t iomcu_firmware_bin_size;

// IOMCU state
static struct {
    serialPort_t *serial;
    bool initialized;
    bool healthy;
    bool firmwareOk;
    uint32_t lastRxTime;
    uint32_t errorCount;
    uint16_t pwmValues[MAX_IOMCU_CHANNELS];
    uint16_t statusFlags;
    bool safetyOff;
} iomcu;

// Communication timeout
#define IOMCU_TIMEOUT_MS 1000
#define IOMCU_TASK_PERIOD_US 20000  // 50Hz

static bool iomcuReadRegisters(uint8_t page, uint8_t offset, uint8_t count, uint16_t *values)
{
    if (!iomcu.serial || count == 0 || count > IOMCU_MAX_REGISTERS) {
        return false;
    }

    // Build read request packet
    iomcuPacket_t pkt;
    iomcuPacketSetCodeCount(&pkt, IOMCU_CODE_READ, count);
    pkt.page = page;
    pkt.offset = offset;
    pkt.crc = iomcuPacketCrc(&pkt);

    // Send request (header only for read)
    uint8_t *data = (uint8_t*)&pkt;
    for (uint8_t i = 0; i < 4; i++) {
        serialWrite(iomcu.serial, data[i]);
    }

    // Wait for response (with timeout)
    uint32_t startTime = millis();
    uint8_t rxBuf[IOMCU_PACKET_SIZE];
    uint8_t rxIdx = 0;
    uint8_t expectedLen = 4 + (count * 2);

    while ((millis() - startTime) < 100 && rxIdx < expectedLen) {
        if (serialRxBytesWaiting(iomcu.serial) > 0) {
            rxBuf[rxIdx++] = serialRead(iomcu.serial);
        }
    }

    if (rxIdx != expectedLen) {
        iomcu.errorCount++;
        return false;
    }

    // Parse response
    iomcuPacket_t *rxPkt = (iomcuPacket_t*)rxBuf;

    // Verify CRC
    if (!iomcuPacketCrcValid(rxPkt)) {
        iomcu.errorCount++;
        return false;
    }

    // Copy values
    memcpy(values, rxPkt->regs, count * sizeof(uint16_t));

    iomcu.lastRxTime = millis();
    return true;
}

static bool iomcuWriteRegisters(uint8_t page, uint8_t offset, uint8_t count, const uint16_t *values)
{
    if (!iomcu.serial || count == 0 || count > IOMCU_MAX_REGISTERS) {
        return false;
    }

    // Build write packet
    iomcuPacket_t pkt;
    iomcuPacketSetCodeCount(&pkt, IOMCU_CODE_WRITE, count);
    pkt.page = page;
    pkt.offset = offset;
    memcpy(pkt.regs, values, count * sizeof(uint16_t));
    pkt.crc = iomcuPacketCrc(&pkt);

    // Send packet
    uint8_t *data = (uint8_t*)&pkt;
    uint8_t len = 4 + (count * 2);
    for (uint8_t i = 0; i < len; i++) {
        serialWrite(iomcu.serial, data[i]);
    }

    return true;
}

static bool iomcuCheckFirmware(void)
{
    // Read firmware CRC from IOMCU
    // TODO: Implement CRC32 firmware verification
    // For now, always force firmware upload on first boot
    iomcu.firmwareOk = false;
    return iomcu.firmwareOk;
}

static bool iomcuUploadFirmware(void)
{
    if (!iomcu.serial) {
        return false;
    }

    LOG_INFO(IOMCU, "Uploading firmware to IOMCU...");

    // Trigger bootloader
    uint16_t magic = REBOOT_BL_MAGIC;
    iomcuWriteRegisters(PAGE_SETUP, REG_SETUP_REBOOT_BL, 1, &magic);

    // Wait for IOMCU to reboot
    delay(200);

    // Upload firmware using bootloader protocol
    bool result = iomcuUploaderUpload(iomcu.serial, iomcu_firmware_bin, iomcu_firmware_bin_size);

    if (result) {
        LOG_INFO(IOMCU, "Firmware upload successful");
        // Wait for IOMCU to boot
        delay(100);
    } else {
        LOG_ERROR(IOMCU, "Firmware upload failed");
    }

    return result;
}

bool iomcuInit(void)
{
    // Find serial port for UART6 (IOMCU)
    serialPortConfig_t *portConfig = findSerialPortConfig(FUNCTION_NONE);  // UART6 not assigned yet
    if (!portConfig) {
        return false;
    }

    // Open serial port at IOMCU baud rate
    iomcu.serial = openSerialPort(SERIAL_PORT_USART6, FUNCTION_NONE,
                                   NULL, NULL, IOMCU_BAUD_RATE,
                                   MODE_RXTX, SERIAL_NOT_INVERTED);

    if (!iomcu.serial) {
        LOG_ERROR(IOMCU, "Failed to open UART6");
        return false;
    }

    // Wait for IOMCU to boot
    delay(50);

    // Verify communication by reading CONFIG page
    uint16_t configRegs[4];
    if (!iomcuReadRegisters(PAGE_CONFIG, REG_CONFIG_PROTOCOL_VERSION, 4, configRegs)) {
        LOG_ERROR(IOMCU, "Failed to communicate with IOMCU");
        closeSerialPort(iomcu.serial);
        iomcu.serial = NULL;
        return false;
    }

    // Verify protocol version
    if (configRegs[REG_CONFIG_PROTOCOL_VERSION] != IOMCU_PROTOCOL_VERSION) {
        LOG_ERROR(IOMCU, "Protocol version mismatch");
        closeSerialPort(iomcu.serial);
        iomcu.serial = NULL;
        return false;
    }

    LOG_INFO(IOMCU, "IOMCU detected: board=0x%04x, channels=%d",
             configRegs[REG_CONFIG_BOARD_TYPE],
             configRegs[REG_CONFIG_MAX_CHANNELS]);

    // Check firmware CRC
    if (!iomcuCheckFirmware()) {
        LOG_WARNING(IOMCU, "Firmware CRC mismatch, uploading new firmware");
        if (!iomcuUploadFirmware()) {
            closeSerialPort(iomcu.serial);
            iomcu.serial = NULL;
            return false;
        }
        // Verify again after upload
        delay(100);
        if (!iomcuCheckFirmware()) {
            LOG_ERROR(IOMCU, "Firmware verification failed after upload");
            closeSerialPort(iomcu.serial);
            iomcu.serial = NULL;
            return false;
        }
    }

    // Initialize PWM values to neutral
    for (uint8_t i = 0; i < MAX_IOMCU_CHANNELS; i++) {
        iomcu.pwmValues[i] = 1500;
    }

    iomcu.initialized = true;
    iomcu.healthy = true;
    iomcu.lastRxTime = millis();

    LOG_INFO(IOMCU, "IOMCU initialized successfully");
    return true;
}

void iomcuTask(timeUs_t currentTimeUs)
{
    UNUSED(currentTimeUs);

    if (!iomcu.initialized || !iomcu.serial) {
        return;
    }

    // Write PWM values to IOMCU
    iomcuWriteRegisters(PAGE_DIRECT_PWM, 0, MAX_IOMCU_CHANNELS, iomcu.pwmValues);

    // Read status
    uint16_t statusRegs[3];
    if (iomcuReadRegisters(PAGE_STATUS, REG_STATUS_FLAGS, 3, statusRegs)) {
        iomcu.statusFlags = statusRegs[REG_STATUS_FLAGS];
        iomcu.safetyOff = (iomcu.statusFlags & STATUS_FLAG_SAFETY_OFF) != 0;
    }

    // Update health
    uint32_t now = millis();
    iomcu.healthy = (now - iomcu.lastRxTime) < IOMCU_TIMEOUT_MS && iomcu.errorCount < 10;
}

bool iomcuIsInitialized(void)
{
    return iomcu.initialized;
}

bool iomcuIsHealthy(void)
{
    return iomcu.initialized && iomcu.healthy;
}

void iomcuWritePwm(uint8_t channel, uint16_t value)
{
    if (channel >= MAX_IOMCU_CHANNELS) {
        return;
    }

    // Clamp to valid range
    if (value < 1000) value = 1000;
    if (value > 2000) value = 2000;

    iomcu.pwmValues[channel] = value;
}

void iomcuWritePwmAll(const uint16_t *values)
{
    for (uint8_t i = 0; i < MAX_IOMCU_CHANNELS; i++) {
        uint16_t value = values[i];
        if (value < 1000) value = 1000;
        if (value > 2000) value = 2000;
        iomcu.pwmValues[i] = value;
    }
}

void iomcuSetOutputMode(uint8_t mode)
{
    uint16_t modeReg = mode;
    iomcuWriteRegisters(PAGE_SETUP, REG_SETUP_OUTPUT_MODE, 1, &modeReg);
}

void iomcuSetPwmRate(uint16_t rate)
{
    iomcuWriteRegisters(PAGE_SETUP, REG_SETUP_PWM_RATE, 1, &rate);
}

void iomcuForceSafetyOff(void)
{
    uint16_t magic = FORCE_SAFETY_OFF_MAGIC;
    iomcuWriteRegisters(PAGE_SETUP, REG_SETUP_FORCE_SAFETY_OFF, 1, &magic);
}

bool iomcuIsSafetyOff(void)
{
    return iomcu.safetyOff;
}

bool iomcuForceUpdate(void)
{
    if (!iomcu.initialized) {
        return false;
    }

    return iomcuUploadFirmware();
}

uint8_t iomcuGetChannelCount(void)
{
    return iomcu.initialized && iomcu.healthy ? MAX_IOMCU_CHANNELS : 0;
}

#endif // USE_IOMCU
